library(tidyverse)
library(magrittr)
library(httr)
library(jsonlite)
library(here)
library(countrycode)
library(raster)
library(sf)
library(rnaturalearth)

h <- here::here

url <- "https://raw.githubusercontent.com/ecohealthalliance/amr-db/master/data/events_db.csv"
events <- GET(url, authenticate("emmamendelsohn", Sys.getenv("GITHUB_PAT")))
events <- read_csv(content(events, "text"))

#-----------------Country-wide data-----------------
# Get iso3c codes for countries

events %<>%
  mutate(study_country = recode(study_country, "england" = "united kingdom")) %>%
  mutate(iso3c = countrycode(sourcevar = study_country,
                             origin = "country.name",
                             destination = "iso3c"))

# Summarize counts
events_by_country <- events %>%
  group_by(iso3c) %>%
  count(name = "n_amr_events") %>%
  ungroup() 
#-----------------World Bank data-----------------
# 2015
# Population and GDP
# SP.POP.TOTL = Population, total
# SM.POP.TOTL = International migrant stock, total (number of people born in a country other than that in which they live. It also includes refugees). United Nations Population Division, Trends in Total Migrant Stock: 2012 Revision.
# NY.GDP.MKTP.CD = GDP (current US$)
# SH.XPD.CHEX.GD.ZS = Current health expenditure (% of GDP) : World Health Organization Global Health Expenditure database

indicator = c("SP.POP.TOTL", 
              "SM.POP.TOTL",
              "NY.GDP.MKTP.CD",
              "SH.XPD.CHEX.GD.ZS")

wbd <- map_df(indicator, function(x){
  tmp <- fromJSON(paste0("http://api.worldbank.org/v2/country/all/indicator/", x, "?date=2015:2015&per_page=20000&format=json"))
  tmp[[2]] %>% 
    dplyr::select(value, countryiso3code) %>%
    mutate(param = tmp[[2]][[1]]$id) %>%
    as_tibble() %>%
    filter(countryiso3code != "")
})

wbd %<>%
  drop_na(value) %>%
  spread(key = param, value = value) %>%
  mutate(SM.POP.TOTL = 100 * SM.POP.TOTL/SP.POP.TOTL) %>% #calc migrant % of population
  rename(population = SP.POP.TOTL,
         migrant_pop_perc = SM.POP.TOTL,
         gdp_dollars = NY.GDP.MKTP.CD,
         health_expend_perc = SH.XPD.CHEX.GD.ZS,
         iso3c = countryiso3code)

#-----------------Observatory of Economic Complexity------------
# 2015
# Visualization: https://atlas.media.mit.edu/en/visualize/tree_map/hs92/export/show/all/2941/2015/
# Values in billions
oec <- read_json("https://atlas.media.mit.edu/hs92/export/2015/show/all/2941/")$data 
oec <- map_df(oec, function(x){
  
  import <- ifelse(is.null(x$import_val), 0, x$import_val)
  export <- ifelse(is.null(x$export_val), 0, x$export_val)
  
  tibble(iso3c = toupper(substr(x$origin_id, 3, 5)), 
         ab_import_dollars = import, 
         ab_export_dollars = export)
}) 

#-----------------Pubcrawler data-----------------
# Pubcrawler reporting effort index, as used in Hotspots II, aggregated by country.
# https://www.nature.com/articles/s41467-017-00923-8#MOESM1
# Values are unitless
pubcrawl_weights <- read_csv(h("data/pubcrawler_country.csv")) %>% # generated by Toph on 2/1/19
  mutate(country = tolower(country),
         country = recode(country, 
                          "belice" = "belize", 
                          "brasil" = "brazil",
                          "cen african rep" = "central african republic", 
                          "czech r" = "czech republic",
                          "dominican r" = "dominican republic", 
                          "england" = "united kingdom",
                          "mauretania" = "mauritania" , 
                          "moracco" = "morocco" ,
                          "morocco (includes western sahara)" = "western sahara",
                          "philippine" = "philippines", 
                          "tunesia" =  "tunisia" ),
         iso3c = countrycode(sourcevar = country,
                             origin = "country.name",
                             destination = "iso3c")) %>%
  drop_na(iso3c) %>% # federal republic of yugoslavia, netherland antilles
  filter(!(iso3c == "MRT" & pubs_sum==0)) %>%
  dplyr::select(-country) 

#-----------------GRITS ProMED-----------------
promed_weights <- read_csv(h("data/promed_mentions.csv")) %>%
  mutate(iso3c = countrycode(sourcevar = country_code,
                             origin = "iso2c",
                             destination = "iso3c")) %>% 
  drop_na(iso3c) %>% # netherland antilles, Serbia and Montenegro, Kosovo, Yugoslavia
  dplyr::select(-country_code, promed_mentions = mentions) 

#-----------------Language by country-----------------
# CIA World Factbook https://www.cia.gov/library/publications/the-world-factbook/fields/402.html
lang <- read_csv(h("data/cia-world-factbook-language.csv"), col_names = "info") %>%
  filter(!str_detect(info, "note"))  %>%
  mutate(desc = rep(c("country", "language"), nrow(.)/2)) 

lang <- lang %>% 
  filter(desc == "country") %>% 
  dplyr::select(country = info) %>%
  bind_cols(lang %>% 
            filter(desc == "language") %>%
              dplyr::select(language = info)) %>%
  mutate(english_spoken = str_detect(language, "English"),
         iso3c = countrycode(sourcevar = country,
                             origin = "country.name",
                             destination = "iso3c")) %>%
  dplyr::select(iso3c, english_spoken) %>%
  drop_na(iso3c) # Akrotiri, Dhekelia, Eswatini, European Union, Kosovo, Saint Martin, Virgin Islands, World

#-----------------Human Consumption data-----------------
# 2014 as stated (https://www.thelancet.com/action/showPdf?pii=S2542-5196%2818%2930186-4)
# From IQVIA MIDAS via ResistanceMap from the Center For Disease Dynamics, Economics & Policy, as provided in Collignon EA 2018 supp data via personal correspondence 
# Values are Total defined daily dose (DDD) per capita
# Defined Daily Dose (DDD): The assumed average maintenance dose per day for a drug used for its main indication in adults.
# there are three fields with human consumption data.  `CCDEP Usage Per Capita (Units of usage are on average 45% of DDD measured by ECDC)` has the most available.

consumption <- readxl::read_xlsx(h("data/Supplementary Table 1 Spreadsheet Data[2].xlsx")) %>%
  dplyr::select(`International Organization for Standardization (ISO)*`, 
                `CCDEP Usage Per Capita (Units of usage are on average 45% of DDD measured by ECDC)`) %>%
  rename(iso3c = `International Organization for Standardization (ISO)*`, 
         human_consumption_ddd =  `CCDEP Usage Per Capita (Units of usage are on average 45% of DDD measured by ECDC)`) %>%
  filter(iso3c != "na") %>%
  drop_na(iso3c, human_consumption_ddd)

#-----------------Livestock Consumption data-----------------
# 2010 
# Supp data from VanBoeckelEA 2015 https://www.pnas.org/content/112/18/5649
livestock <- read_csv(h("data/VanBoeckelEA_total_annual_sales.csv")) %>%
  group_by(country) %>%
  summarize(livestock_ab_sales_kg = mean(livestock_ab_sales_kg)) %>% # average multiple values by country (all are very close)
  ungroup() %>%
  mutate(iso3c = countrycode(sourcevar = country,
                             origin = "country.name",
                             destination = "iso3c")) %>%
  dplyr::select(-country)
#-----------------Tourism data-----------------
# 2015
# World Tourism Organization (2019), Compendium of Tourism Statistics dataset [Electronic], UNWTO, Madrid, data updated on 11/01/2019.
# Outbound tourism downloaded from https://www.e-unwto.org/doi/suppl/10.5555/unwtotfb0000290019952017201901
tour_outbound <- readxl::read_xlsx(h("data/0000290019952017201901.xlsx"), sheet = 1, skip = 5) %>% # Outbound tourism - Departures of visitors (overnight visitors -tourists- and same-day visitors -excursionists-)… Thousands
  dplyr::select(COUNTRY, tourism_outbound = `2015`) %>%
  filter(tourism_outbound != "..")
tour_inbound <- readxl::read_xlsx(h("data/0000270019952017201901.xlsx"), sheet = 1, skip = 5) %>% # Inbound tourism - Arrivals of non-resident visitors (overnight visitors -tourists- and same-day visitors -excur… Thousands
  dplyr::select(COUNTRY, tourism_inbound = `2015`) %>%
  filter(tourism_inbound != "..")

tourism <- full_join(tour_outbound, tour_inbound) %>%
  mutate_at(vars("tourism_outbound", "tourism_inbound"), ~as.numeric(.)) %>%
  mutate(iso3c = countrycode(sourcevar = COUNTRY,
                             origin = "country.name",
                             destination = "iso3c")) %>%
  dplyr::select(-COUNTRY) %>%
  drop_na(iso3c)

#-----------------All countries-----------------
all_countries <- map_data("world") %>%
  mutate(iso3c = countrycode(sourcevar = region,
                             origin = "country.name",
                             destination = "iso3c"))  %>%
  dplyr::select(iso3c) %>% drop_na() %>% distinct() 

#-----------------All data-----------------
amr <- all_countries %>%
  left_join(events_by_country) %>%
  mutate(n_amr_events = replace_na(n_amr_events, 0)) %>%
  left_join(pubcrawl_weights) %>%
  left_join(promed_weights) %>%
  left_join(wbd) %>%
  left_join(oec) %>%
  left_join(lang) %>%
  left_join(consumption) %>%
  left_join(livestock) %>%
  #left_join(livestock3) %>%
  left_join(tourism) %>%
  #left_join(fao) %>%
  mutate(n_amr_events = ifelse(is.na(n_amr_events), 0 , n_amr_events),
         country = countrycode::countrycode(sourcevar = iso3c,
                                            origin = "iso3c",
                                            destination = "country.name"), 
         region = countrycode::countrycode(sourcevar = iso3c,
                                           origin = "iso3c",
                                           destination = "region"), 
         continent = countrycode::countrycode(sourcevar = iso3c,
                                              origin = "iso3c",
                                              destination = "continent"))

# make sure no event or consumption data lost
setdiff(events$iso3c, amr$iso3c)
setdiff(consumption$iso3c, amr$iso3c)
setdiff(livestock$iso3c, amr$iso3c)

# Post process
amr %<>%
  mutate(ab_export_perc = 100 * ab_export_dollars/gdp_dollars,
         ab_import_perc = 100 * ab_import_dollars/gdp_dollars,
         livestock_consumption_kg_per_capita = livestock_ab_sales_kg/population,
         gdp_per_capita = gdp_dollars/population,
         tourism_outbound_perc = 100 * (tourism_outbound*1000)/population,
         tourism_inbound_perc = 100 * (tourism_inbound*1000)/population,
         pubs_sum_per_capita = pubs_sum/population,
         promed_mentions_per_capita = promed_mentions/population
  ) %>%
  dplyr::select(-ab_export_dollars, -ab_import_dollars, -tourism_outbound, -tourism_inbound, -livestock_ab_sales_kg)

write_csv(amr, h("data/country-level-amr.csv"))
