---
title: "Data Quantities"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(drake)
library(tidyverse)
loadd(model_data_with_na, model_data, imputed_data)
```

Look at NA values in raw data
```{r}
map_int(model_data_with_na, ~sum(!is.na(.)))
model_data_with_na %>% 
  filter(pubcrawl_per_capita == 0 | is.na(pubcrawl_per_capita)) %>%
  nrow()
model_data_with_na %>% 
  filter(promed_mentions_per_capita == 0 | is.na( promed_mentions_per_capita)) %>%
  nrow()
model_data_with_na %>% 
  filter(ab_export_per_capita == 0 | is.na( ab_export_per_capita)) %>%
  nrow()

```

Look at NA values and distributions  post-NA processing

```{r}
map_int(model_data, ~sum(!is.na(.)))
map_lgl(model_data, ~any(is.infinite(.))) # confirm no infinite values
model_data %>%
  select(-iso3c, -n_amr_events, -english_spoken) %>%
  gather() %>%
  ggplot(aes(x = value)) +
  geom_histogram() + 
  facet_wrap(key~., scales = "free")
model_data %>%
  dplyr::select(-iso3c, -ln_livestock_pcu, -ln_ab_import_per_capita, -ab_export_bin, -english_spoken) %>%
  PerformanceAnalytics::chart.Correlation(., histogram = TRUE, pch = 19, method = "spearman")

```

Look at imputed data

```{r}
plot(imputed_data) # On convergence, the different streams should be freely intermingled with one another, without showing any definite trends. Convergence is diagnosed when the variance between different sequences is no larger than the variance within each individual sequence.
show_imputes(imputed_data, m = imputed_data[["m"]], raw = model_data)
imp <- complete(imputed_data)
imp %>%
  dplyr::select(-iso3c) %>%
  PerformanceAnalytics::chart.Correlation(., histogram = TRUE, pch = 19, method = "spearman")
```

